function m(b,a,c,d){b.m.pb(b.ub,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.bf()._OnMessageFromDOM({type:"event",component:b.ub,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function p(b,a,c){b.m.B(b.ub,a,c)}function v(b,a){for(const [c,d]of a)p(b,c,d)}function w(b){b.Zb||(b.m.Ec(b.le),b.Zb=!0)}window.va=class{constructor(b,a){this.m=b;this.ub=a;this.Zb=!1;this.le=()=>this.Sa()}qd(){}Sa(){}};
window.Pf=class{constructor(){this.md=-1}j(){-1!==this.md&&(self.clearTimeout(this.md),this.md=-1)}};"use strict";function aa(b,a){p(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Wb}
window.ud=class extends self.va{constructor(b,a){super(b,a);this.Xa=new Map;this.sb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.sb&&d.parentElement.removeChild(d);this.Xa.delete(c)}],["set-visible",c=>{if(this.sb){var d=this.Xa.get(c.elementId),e=d.Wb;d.Vd?e.style.display=c.isVisible?"":"none":d.wf=!!c.isVisible}}],["update-position",c=>{if(this.sb){var d=this.Xa.get(c.elementId),e=d.Wb,f=this.m;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.Bf=g;g=f.wd(g);g!==d.Ia&&(e.remove(),f.wc(g).appendChild(e),d.Ia=g,f.Nc());c=c.htmlZIndex;c!==d.Wc&&(d.Wc=c,f.Nc());d.Vd||(d.Vd=!0,d.wf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ff?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.Jf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const fa={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ha(b){b=await ia(b);return(new TextDecoder("utf-8")).decode(b)}
function ia(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let D=0;window.RealFile=window.File;const E=[],G=new Map,H=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.wa=class b{constructor(a){this.ba=a.Lf;this.za=null;this.aa="";this.fb=a.If;this.Kb={};this.Za=this.ua=null;this.Wa=[];this.na=null;this.Zd=!0;this.M=[];this.fd=[];this.gd=!1;this.me=()=>this.$e();this.Yc=!1;this.Sd=0;this.zb=null;this.eb=-1;this.Af=()=>this.lf();this.Hb=new Set;this.nd=null;this.ne=[];this.A=a.pe;this.$b="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;ca&&(this.ba=!1);if("cordova"===this.A&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Qa()?self.chrome.webview.addEventListener("message",c=>this.Hd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Hd(c));this.cc=this.ra=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.qf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.ff());this.B("runtime","cordova-fetch-local-file",c=>this.gf(c));this.B("runtime","create-job-worker",()=>this.hf());this.B("runtime","send-wrapper-extension-message",c=>this.pf(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Qb(a)):this.Qb(a)}j(){this.Fc();this.za&&(this.za=this.za.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Za&&(this.Za.j(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}xd(){return this.M[0].canvas}wd(a){return Math.min(a,this.M.length-1)}wc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Ne(){return ba&&"cordova"===this.A}nb(){const a=navigator.userAgent;return ba&&oa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Le(){return y}yd(){return y&&oa.has(this.A)}Ad(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}Qa(){return this.Ad()||"xbox-uwp-webview2"===this.A}async Qb(a){this.ba&&!await ea()&&(this.ba=!1);"macos-wkwebview"===this.A?this.qb({type:"ready"}):this.Qa()&&(this.sf(),this.ne=(await this.ef()).registeredComponentIds);if("playable-ad"===this.A){this.ra=self.c3_base64files;this.cc={};await this.Xe();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.cc.hasOwnProperty(c)?a.hb[d]={Ff:!0,Jf:this.cc[c]}:this.ra.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.ra[c]))}a.rc=
[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ec(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.Hf?this.aa=a.Hf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Nf&&(this.Kb=a.Nf);c=new MessageChannel;this.za=c.port1;this.za.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.kf(d));this.zb=
new self.Oe(this);await qa(this.zb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.df(a,c.port2):await this.cf(a,c.port2)}Hc(a){a=this.Kb.hasOwnProperty(a)?this.Kb[a]:a.endsWith("/workermain.js")&&this.Kb.hasOwnProperty("workermain.js")?this.Kb["workermain.js"]:"playable-ad"===
this.A&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async tc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.$b)return a=await this.Mb(d.Ef?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}pa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}vc(){return this.Qa()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}Fd(a){var c=this.aa,d=location.href,e=this.pa(),f=this.ha(),g=this.vc(),
h=window.devicePixelRatio,k=b.mb(),l=a.Uf,q=window.cr_previewImageBlobs||this.ra,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.pe;var Z=(new URLSearchParams(self.location.search)).has("debug"),F=this.zb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:q,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,exportType:a,isDebug:Z,
ife:!!self.Sf,jobScheduler:{inputPort:F.Xc,outputPort:F.ed,maxNumWorkers:F.xf},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.$b,isiOSCordova:this.Ne(),isiOSWebView:this.nb(),isWindowsWebView2:this.Ad(),isAnyWebView2Wrapper:this.Qa(),wrapperComponentIds:this.ne,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async df(a,c){const d=this.Hc(a.Mf);"preview"===
this.A?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,q)=>{const r=t=>{this.ua.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():q()};this.ua.addEventListener("message",r);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ua=await this.tc(d,this.aa,{type:"module",name:"Runtime",Ef:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);
const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.rc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.A)for(let l=0,q=a.qc.length;l<q;++l){const r=a.qc[l],t=r[0];if(t===a.od||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.ua.postMessage(Object.assign(this.Fd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.qc,mainProjectScript:a.od,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ra(this.zb)]);this.Wa=E.map(l=>new l(this));this.Ed();sa(e);ta(g);ua(this.na);self.c3_callFunction=(l,q)=>{var r=this.na;return r.m.Bd(r.ub,"js-invoke-function",{name:l,params:q})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async cf(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=E.map(h=>new h(this));this.Ed();sa(d);ta(e);e=a.hb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.rc)){var f=[...a.rc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.od;const g=a.qc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.A||e[h]||this.Jd(h,"main script did not run to completion")}catch(l){this.Jd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ta(k),await z(k);"preview"===this.A&&"object"!==typeof self.Of.Qf?(this.Sb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Fd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ka}),ua(this.na),this.Gd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,a))}Jd(a,c){this.Sb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Gd(){this.Sb()}Sb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async hf(){const a=await xa(this.zb);return{outputPort:a,transferables:[a]}}qf(a){if(!this.Yc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Zd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Zd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:q}=this.M.pop();q.remove();this.ba&&!d?this.fd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,q=c-this.M.length;l<q;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,sa(c),ta(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.ud&&l.sb)for(const q of l.Xa.values())e=l.m.wd(q.Bf),f=q.Ia,-1!==
e&&-1!==f&&e!==f&&(f=q.Wb,f.remove(),l.m.wc(e).appendChild(f),q.Ia=e);this.Nc();return{addedCanvases:a,transferables:k}}ff(){for(const a of this.fd)a.remove();this.fd.length=0}Nc(){this.gd||(this.gd=!0,this.Ec(this.me))}$e(){this.Id(this.me);this.gd=!1;let a=[];for(var c of this.Wa)if(c instanceof window.ud){var d=c.sb?[...c.Xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ia,l=h.Ia;return k!==l?k-l:g.Wc-h.Wc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ia!==c&&(this.Dd(c,a.slice(d,
e)),c=g.Ia,d=e)}d<e&&this.Dd(c,a.slice(d,e))}Dd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Wb);var d=new Set(c);a=this.wc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}bf(){if(this.ba)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}Bd(a,c,d,e,f){const g=ja++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.za.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.jf(a);if("result"===c)this.mf(a);else if("runtime-ready"===c)this.nf();else if("alert-error"===c)this.Sb(),alert(a.message);else if("creating-runtime"===c)this.Gd();else throw Error(`unknown message '${c}'`);}jf(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Rb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Rb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Rb(f,!1,""+h)}):this.Rb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Rb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.za.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}mf(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Da(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}Ed(){for(const a of this.Wa)if("runtime"===a.ub){this.na=a;return}throw Error("cannot find runtime DOM handler");
}kf(a){this.pb("debugger","message",a)}nf(){for(const a of this.Wa)a.qd()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static Kd(a){pa=!!a}Ec(a){this.Hb.add(a);this.Mc()}Id(a){this.Hb.delete(a);0===this.Hb.size&&this.Fc()}Mc(){-1===this.eb&&0<this.Hb.size&&(this.eb=requestAnimationFrame(this.Af))}Fc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}lf(){this.eb=-1;for(const a of this.Hb)a();this.Mc()}Ga(a){this.na.Ga(a)}Ra(a){this.na.Ra(a)}Lc(){this.na.Lc()}Pb(a){this.na.Pb(a)}Me(){return!!fa["audio/webm; codecs=opus"]}async tf(a){a=
await this.Bd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Te(a){this.Yc=!0;this.Sd=a}Ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}zd(a){return!this.Ke(a)}async Ta(a){return"cordova"===this.A&&(a.startsWith("file:")||this.$b&&this.zd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Mb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async gf(a){const c=a.filename;switch(a.as){case "text":return await this.Ge(c);
case "buffer":return await this.Mb(c);default:throw Error("unsupported type");}}td(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ge(a){a=await this.td(a);return await ha(a)}Gc(){if(B.length&&!(8<=D)){D++;var a=B.shift();this.Ye(a.filename,a.Kf,a.Df)}}Mb(a){return new Promise((c,d)=>{B.push({filename:a,Kf:e=>{D--;this.Gc();c(e)},Df:e=>{D--;this.Gc();d(e)}});this.Gc()})}async Ye(a,c,d){try{const e=
await this.td(a),f=await ia(e);c(f)}catch(e){d(e)}}Hd(a){if("entered-fullscreen"===a)b.Kd(!0),I(this.na);else if("exited-fullscreen"===a)b.Kd(!1),I(this.na);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.nd(a),this.nd=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}pf(a){this.qb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,
params:a.params||[],asyncId:a.asyncId})}qb(a){this.Qa()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}sf(){window.moveTo=(a,c)=>{this.qb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.qb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}ef(){return this.Qa()?new Promise(a=>{this.nd=a;this.qb({type:"wrapper-init"})}):
Promise.resolve()}async Xe(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.We(c,d));await Promise.all(a)}async We(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.cc[a]=c.str;else{let d=await this.af(c);d||(d=this.Ze(c));this.ra[a]=d}}async af(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ze(a){a=this.rf(a);return this.Ve(a.data,a.Gf)}rf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Gf:a,data:d}}Ve(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.wa,ya=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},za={dispatchUserScriptEvent:!0},Aa={dispatchRuntimeEvent:!0};function Ba(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Ca(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Da(b){b=URL.createObjectURL(b);try{return await Ca(b)}finally{URL.revokeObjectURL(b)}}function Ea(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Fa=new Set(["input","textarea","datalist","select"]),Ga=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ga.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ha(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ia(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Da(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Da(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ja=!1;document.addEventListener("pause",()=>Ja=!0);document.addEventListener("resume",()=>Ja=!1);function sa(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function ta(b){b.addEventListener("selectstart",Ha);b.addEventListener("gesturehold",Ha);b.addEventListener("touchstart",Ha)}function ua(b){b.Rd=!0;b.ad=b.m.pa();b.Ab=b.m.ha()}
function I(b){if(!b.la){var a=J.mb();a&&"any"!==b.kd&&Ka(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ha()})}}async function La(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ma(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Na(b){return await self.C3_GetSvgImageSize(b.blob)}function Oa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Pa(b){self.setTimeout(()=>{b.Qd=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Qa(b,!0)),document.addEventListener("resume",()=>Qa(b,!1))):document.addEventListener("visibilitychange",()=>Qa(b,"hidden"===document.visibilityState));b.hc=!("hidden"!==document.visibilityState&&!Ja);return{isSuspended:b.hc}}
function Ra(b){b.Md||(b.Md=!0,window.addEventListener("deviceorientation",a=>{b.la||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.la||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Sa(b){b.Ld||(b.Ld=!0,window.addEventListener("devicemotion",a=>{if(!b.la){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ta(b){await Ba(b.url)}
function Ua(b,a){b.Td=a.message;-1===b.Rc&&(b.Rc=setTimeout(()=>{b.Rc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Td)},250))}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.pa(),innerHeight:b.ha()})}
function Qa(b,a){b.hc!==a&&((b.hc=a)?b.m.Fc():b.m.Mc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Wa(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.la){var d=ya.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.la||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.la){var d=0;"mouse"===c.pointerType&&(d=b.cd);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ca,pageX:c.pageX,pageY:c.pageY+b.Ca,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.cd=c.buttons)}}function Xa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ca=a))}}
function Ya(b,a,c,d){const e=b.pa(),f=b.ha();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:b.m.vc()}):10>d&&Za(b,e,f,d+1)}function Za(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>Ya(b,a,c,d),48)}
function Ka(b){b=b.kd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function $a(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Da(class extends self.va{constructor(b){super(b,"runtime");this.Rd=!1;this.gb=-1;this.kd="any";this.hc=this.Ld=this.Md=!1;this.nc=document.createElement("div");this.nc.className="c3-screen-reader-text";this.nc.setAttribute("aria-live","polite");document.body.appendChild(this.nc);this.Ka=null;this.la=!1;this.Td="";this.Rc=-1;this.Qd=!1;this.ad=b.pa();this.Ab=b.ha();this.Ca=this.Jb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>La(c));b.B("runtime","raster-svg-image",c=>Ma(c));b.B("runtime","get-svg-image-size",c=>Na(c));b.B("runtime","set-target-orientation",c=>{this.kd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Oa(c));b.B("runtime","go-to-script",c=>Oa(c));b.B("runtime","before-start-ticking",()=>Pa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ra(this));b.B("runtime","enable-device-motion",()=>Sa(this));b.B("runtime","add-stylesheet",c=>Ta(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.nc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.la=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.xd().style.display="";this.m.Te(c.duration)});b.B("runtime","export-to-video-progress",c=>Ua(this,c));b.B("runtime","exported-to-video",c=>{window.Cf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.Cf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ea(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.cd=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ia,{passive:!1});window.addEventListener("wheel",Ia,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.la&&this.Rd){var c=this.pa();var d=this.ha();if(this.m.yd()){if(this.Qd){if(this.ad===
c&&d<this.Ab){this.Jb=this.Ab-d;Xa(this,this.Ab,this.Jb);c=void 0;break a}0<this.Jb&&(this.Jb=0,Xa(this,d,this.Jb))}this.ad=c;this.Ab=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb(),cssDisplayMode:this.m.vc()});this.m.nb()&&(-1!==this.gb&&clearTimeout(this.gb),Ya(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Va(this,c));window.addEventListener("webkitfullscreenerror",c=>Va(this,c));window.addEventListener("mozfullscreenerror",c=>Va(this,c));if(b.nb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.ec=new WeakSet;this.ya=!1}qd(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,Aa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},Aa);this.cd=0});window.addEventListener("focusin",a=>{a=a.target;(Fa.has(a.tagName.toLowerCase())||Ea(a))&&m(this,"keyboard-blur",null,Aa)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
za));window.addEventListener("mousemove",a=>M(this,"mousemove",a,za));window.addEventListener("mouseup",a=>M(this,"mouseup",a,za));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.la||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ca,pageX:a.pageX,pageY:a.pageY+this.Ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
$a(a.target)&&document.activeElement&&!$a(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Lc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.Le()&&!this.m.yd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Xa(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}));this.m.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}pa(){return this.m.pa()}ha(){return this.m.ha()}Lc(){var b=
[...this.$a];this.$a.clear();if(!this.ya)for(const a of b)(b=a.play())&&b.catch(()=>{this.ec.has(a)||this.$a.add(a)})}Ga(b){if("function"!==typeof b.play)throw Error("missing play function");this.ec.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.ec.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.ec.add(b)}Pb(b){this.ya=!!b}});"use strict";
async function qa(b){if(b.uf)throw Error("already initialised");b.uf=!0;var a=b.Aa.Hc(("playable-ad"===b.Aa.A?b.Aa.fb:"")+"dispatchworker.js");b.Qc=await b.Aa.tc(a,b.tb,{name:"DispatchWorker"});a=new MessageChannel;b.Xc=a.port1;b.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ed=await xa(b)}function ra(b){return[b.Xc,b.ed]}
async function xa(b){const a=b.$d.length;var c=b.Aa.Hc(("playable-ad"===b.Aa.A?b.Aa.fb:"")+"jobworker.js");c=await b.Aa.tc(c,b.tb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Qc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.$d.push(c);return e.port1}
self.Oe=class{constructor(b){this.Aa=b;this.tb=b.aa;this.tb="preview"===b.A?this.tb+"workers/":this.tb+b.fb;this.xf=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.$d=[];this.ed=this.Xc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.wa({Lf:!0,Mf:"workermain.js",hb:["scripts/c3runtime.js"],qc:[],od:"",If:"scripts/",rc:["box2d.wasm.js"],pe:"html5"}));"use strict";const ab=180/Math.PI;
async function bb(b,a){if(a.isiOSCordova||a.isSafari)b.jc=!0;b.ld=a.timeScaleMode;b.ee=["equalpower","HRTF","soundfield"][a.panningModel];b.Pd=["linear","inverse","exponential"][a.distanceModel];b.fe=a.refDistance;b.de=a.maxDistance;b.he=a.rolloffFactor;if(b.m.Yc)b.jc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Sd)});else{var c={latencyHint:a.latencyHint};b.ke||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&cb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function db(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,q=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.ae=g.slice(0);eb(b,g);try{b.R=await fb(b,c,d,e,g,f);if(q){P(b.R,!0);var u=b.R,Z=q.x,F=q.y,vb=q.z,wb=q.angle,la=q.innerAngle,ma=q.outerAngle,na=q.outerGain;if(u.yb){gb(u,Z,F,vb,wb);var C=self.jb.Ue;
u.sa[0]!==C(la)&&(u.sa[0]=C(la),u.F.coneInnerAngle=C(la));u.sa[1]!==C(ma)&&(u.sa[1]=C(ma),u.F.coneOuterAngle=C(ma));u.sa[2]!==na&&(u.sa[2]=na,u.F.coneOuterGain=na)}q.hasOwnProperty("uid")&&(b.R.qa=q.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),hb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=g.join(" ");d=b.Gb.get(c);if(!d)throw Error("expected pending tag");d.pd--;0===d.pd&&(d.resolve(),b.Gb.delete(c))}w(b)}
async function ib(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await kb(b,c);for(const h of R(b,c))if(!h.xa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Ya=g;h.je=a}S(b)}async function lb(b,a){const c=a.tags;a=a.rate;await kb(b,c);for(const d of R(b,c))d.ma!==a&&(d.ma=a,d.Ha())}async function mb(b,a){const c=a.tags;a=a.pos;await kb(b,c);for(const d of R(b,c))d.Bc(a)}
async function nb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await fb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ob(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function pb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ve(b,...e);else if("delay"===c)d=new self.te(b,...e);else if("convolution"===c){var g=d=new self.se(b,f.ia,...e),h=a.bufferType;g.Nd=a.bufferOriginalUrl;g.Od=h}else if("flanger"===c)d=
new self.we(b,...e);else if("phaser"===c)d=new self.ye(b,...e);else if("gain"===c)d=new self.xe(b,...e);else if("stereopan"===c)d=new self.Ae(b,...e);else if("tremolo"===c)d=new self.Be(b,...e);else if("ringmod"===c)d=new self.ze(b,...e);else if("distortion"===c)d=new self.ue(b,...e);else if("compressor"===c)d=new self.re(b,...e);else if("analyser"===c)d=new self.qe(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ka.get(h);l||(l=[],g.ka.set(h,l));d.Yd=l.length;d.jd=
h;l.push(d);qb(g,h)}rb(b)}
async function sb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ea()&&1===c||!e.Ea()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ka.values())for(const g of f)g.j();b.ka.clear();b.oc=a.timeScale;b.Tc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.ya=a.isSilent;b.m.Pb(b.ya);b.dc=a.masterVolume;b.Va.gain.value=
b.dc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>pb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>tb(b,f,c)));S(b)}
async function ub(b,a){try{const c=b.g.suspend(a.time);b.Xd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.Xd=!0);await c}catch(c){yb(c)}}
function cb(b){b.Yb||(b.Vc=!1,window.addEventListener("pointerup",b.Ba,!0),window.addEventListener("touchend",b.Ba,!0),window.addEventListener("click",b.Ba,!0),window.addEventListener("keydown",b.Ba,!0),b.Yb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ja)if(g.lb()===c)return await zb(g),g;if(f)return null;if(e&&(b.jc||b.Wd)){f=0;for(let h=0,k=b.ja.length;h<k;++h)g=b.ja[h],b.ja[f]=g,g.Ea()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.ke;e&&f&&(b.Wd=!0);c=!e||b.jc||f?new self.Ee(b,a,c,d,e,f):new self.Ce(b,a,c,d,e);b.ja.push(c);await zb(c);b.ce.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.ce.add(a));return c}
function Ab(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Bb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.fa()}function qb(b,a){a=a.toLowerCase();let c=b.fa();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.fa()):e.U(d[f+1].N())}}for(const f of Cb(b,a))e=f,d=c,e=e.ea||e.F||e.G,e.disconnect(),e.connect(d);b.La&&b.bd===a&&(b.La.disconnect(),b.La.connect(c))}
function*Cb(b,a){if(a)for(const c of b.H)Ab(0<c.oa.length?c.oa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Db(b,a,c){return c?b.m.tf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Eb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.oa;var c=a;for(const e of c){c=!1;for(const f of b)if(Ab(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function fb(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.sc()||f))return g.oa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Oc?new self.De(a.u,a,e):new self.Fe(a.u,a,e);b.H.push(e);return e}
function eb(b,a){a=a.join(" ");let c=b.Gb.get(a);if(!c){let d=null;c={pd:0,promise:new Promise(e=>d=e),resolve:d};b.Gb.set(a,c)}c.pd++}function kb(b,a){return(b=b.Gb.get((0===a.length?b.ae:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Fb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function rb(b){b.Zc||(b.Zc=!0,Promise.resolve().then(()=>Gb(b)))}
function Gb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Zc=!1}
async function tb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await fb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),hb(b,d));c.Play(k,l,q,0);a.isPlaying||c.ob();c.Jc(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.va{constructor(b){super(b,"audio");this.Va=this.g=null;this.Yb=this.Vc=!1;this.Ba=()=>{if(!this.Vc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Yb&&(this.Vc=!0,window.removeEventListener("pointerup",this.Ba,!0),window.removeEventListener("touchend",this.Ba,!0),window.removeEventListener("click",this.Ba,!0),window.removeEventListener("keydown",
this.Ba,!0),this.Yb=!1)}};this.ja=[];this.H=[];this.R=null;this.ae=[];this.ce=new Set;this.be=-1;this.Gb=new Map;this.dc=1;this.ya=!1;this.ld=0;this.oc=1;this.Tc=0;this.ee="HRTF";this.Pd="inverse";this.fe=600;this.de=1E4;this.he=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Wd=this.jc=!1;this.ke=this.m.Me();this.ka=new Map;this.Ua=new Set;this.Xd=this.Zc=!1;this.bd="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.bd=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Bb(this,this.bd))};this.Vb=null;self.C3Audio_GetOutputStream=()=>{this.Vb||(this.Vb=this.g.createMediaStreamDestination(),this.Va.connect(this.Vb));return this.Vb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>bb(this,a)],["play",a=>db(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Fa()}],["stop-all",()=>{for(const a of this.H)a.Fa()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.ob():d.Ob();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>ib(this,a)],["set-master-volume",a=>{this.dc=a.vol;this.Va.gain.value=this.dc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Hb(d,a)}],["set-silent",a=>{this.ya=a.isSilent;this.m.Pb(this.ya);for(const c of this.H)c.Tb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.Cc(a)}],["set-playback-rate",a=>lb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),hb(d,a)}],["seek",a=>mb(this,a)],["preload",a=>nb(this,a)],["unload",a=>ob(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Dc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>pb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ka.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);rb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ka.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ka.delete(a);qb(this,a)}}],["tick",a=>{this.oc=a.timeScale;this.Tc=a.gameTime;this.be=a.tickCount;if(0!==this.ld)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&gb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>sb(this,a)],["offline-render-audio",a=>ub(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}fa(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.fa()}Nb(){return this.ya}Ga(b){this.m.Ga(b)}Ra(b){this.m.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.be,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.jd,index:c.Yd,peak:c.cb,rms:c.ge,binCount:c.l.frequencyBinCount,freqBins:c.Ud}))});0===a.length&&0===this.Ua.size&&this.Zb&&(this.m.Id(this.le),this.Zb=!1)}static Ue(b){return b*ab}static vd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Pe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.wa.Da(self.jb);"use strict";function zb(b){b.bc||(b.bc=b.Ic());return b.bc}self.rd=class{constructor(b,a,c,d,e){this.u=b;this.zf=a;this.Na=c;this.T=d;this.vf=e;this.Oc="";this.bc=null}j(){this.bc=this.u=null}Ic(){}V(){return this.u.V()}xc(){return this.zf}lb(){return this.Na}uc(){return this.T}Ea(){return this.vf}ga(){}};"use strict";
self.Ce=class extends self.rd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Oc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Bb=this.Cb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Fb=this.V().createGain();this.Eb=null;this.L.addEventListener("canplay",()=>{this.Cb&&(this.Cb(),this.Bb=this.Cb=null);!this.Eb&&this.L&&(this.Eb=this.V().createMediaElementSource(this.L),this.Eb.connect(this.Fb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Bb&&(this.Bb(f),this.Bb=this.Cb=null)})}j(){Eb(this.u,this);this.Fb.disconnect();this.Fb=null;this.Eb.disconnect();this.Eb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Ic(){return new Promise((b,a)=>{this.Cb=b;this.Bb=a;this.L.src=this.Na})}W(){return this.L}ga(){return this.L.duration}};"use strict";
async function Ib(b){if(b.Ja)return b.Ja;var a=b.u.m;if("cordova"===a.A&&a.zd(b.Na)&&a.$b)b.Ja=await a.Mb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Jb(b){if(b.ia)return b.ia;b.ia=await Db(b.u,b.Ja,b.yf);b.Ja=null}
self.Ee=class extends self.rd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Oc="webaudio";this.ia=this.Ja=null;this.yf=!!f}j(){Eb(this.u,this);this.ia=this.Ja=null;super.j()}async Ic(){try{await Ib(this),await Jb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Kb=0;
function P(b,a){a=!!a;b.yb!==a&&(b.yb=a,b.yb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.ee,b.F.distanceModel=b.u.Pd,b.F.refDistance=b.u.fe,b.F.maxDistance=b.u.de,b.F.rolloffFactor=b.u.he),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.fa())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.fa())))}
function Q(b,a){a=!!a;b.ac!==a&&(b.ac=a,b.ac?(P(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.fa())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.fa())))}function hb(b,a){b.ac&&b.hd!==a&&(b.ea.pan.value=a,b.hd=a)}function T(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.yc()}function Hb(b,a){a=!!a;b.xa!==a&&(b.xa=a,b.Tb())}
function gb(b,a,c,d,e){if(b.yb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.$c?b.u.Tc:performance.now()/1E3}
self.sd=class{constructor(b,a,c){this.u=b;this.P=a;this.oa=c;this.Ub=Kb++;this.G=this.V().createGain();this.G.connect(this.fa());this.F=null;this.yb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.sa=[0,0,0];this.ea=null;this.ac=!1;this.hd=0;this.I=!0;this.Y=this.ta=this.J=!1;this.Oa=1;this.xa=!1;this.ma=1;b=this.u.ld;this.$c=1===b&&!this.Ea()||2===b;this.Ya=this.qa=-1;this.je=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}fa(){return Bb(this.u,0<this.oa.length?this.oa[0]:"")}xc(){return this.P.xc()}lb(){return this.P.lb()}uc(){return this.P.uc()}Ea(){return this.P.Ea()}O(){}sc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Pa(){}ga(){return this.P.ga()}Play(){}Fa(){}ob(){}Ob(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.je&&this.Fa(),Fb(this.u,"fade-ended",this.oa,this.Ub))}yc(){const b=this.Oa;return isFinite(b)?b:0}Nb(){return this.u.Nb()}Tb(){}Cc(){}Ha(){}Bc(){}Dc(){}zc(){}kb(){var b=
this.Ub,a=this.oa,c=this.ga(),d=-1===this.Ya?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Pa(),playbackRate:this.ma,uid:this.qa,bufferOriginalUrl:this.xc(),bufferUrl:"",bufferType:this.uc(),isMusic:this.Ea(),isLooping:this.Y,isMuted:this.xa,resumePosition:this.zc(),pan:f,stereoPan:this.ea?
this.hd:null}}Jc(b){var a=b.playbackRate;this.ma!==a&&(this.ma=a,this.Ha());Hb(this,b.isMuted)}};"use strict";
self.De=class extends self.sd{constructor(b,a,c){super(b,a,c);this.P.Fb.connect(this.G);this.P.onended=()=>this.Kc()}j(){this.Fa();this.P.Fb.disconnect();super.j()}W(){return this.P.W()}Kc(){this.I=!0;this.qa=-1;Fb(this.u,"ended",this.oa,this.Ub)}O(){return this.W().ended}sc(){return this.I?!0:this.O()}Pa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.xa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.u.Ga(d);this.J=this.I=!1;this.Y=b;this.ma=1}Fa(){const b=this.W();b.paused||b.pause();this.u.Ra(b);this.I=!0;this.J=!1;this.qa=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Ra(b);this.J=!0}}Ob(){!this.J||this.I||this.O()||(this.u.Ga(this.W()),this.J=!1)}Tb(){this.W().muted=this.xa||this.Nb()}Cc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.ma;this.$c&&(b*=this.u.oc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}Bc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}zc(){return this.Pa()}Dc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.u.Ga(this.W()),this.ta=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.rb=null}
self.Fe=class extends self.sd{constructor(b,a,c){super(b,a,c);this.s=null;this.fc=d=>this.Kc(d);this.Uc=!0;this.rb=null;this.S=this.ic=this.kc=0;this.dd=1}j(){this.Fa();V(this);this.fc=null;super.j()}Kc(b){this.J||this.ta||b.target!==this.rb||(this.I=this.Uc=!0,this.qa=-1,V(this),Fb(this.u,"ended",this.oa,this.Ub))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Uc}sc(){return!this.s||this.I?!0:this.O()}Pa(){let b;b=this.J?this.S:this.ic+(U(this)-this.kc)*this.ma;this.Y||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.xa=!1;this.dd=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ia;this.s.connect(this.G);this.rb=this.s;this.s.onended=this.fc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Uc=!1;this.Y=b;this.ma=1;this.kc=U(this);this.ic=c}Fa(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}ob(){this.J||this.I||this.O()||(this.S=this.Pa(),this.Y&&(this.S%=this.ga()),this.J=!0,this.s.stop(0))}Ob(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.J=!1)}yc(){return super.yc()*this.dd}Tb(){this.dd=this.xa||this.Nb()?0:1;T(this,this.Oa)}Cc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.ma;this.$c&&(b*=this.u.oc);this.s&&(this.s.playbackRate.value=b)}Bc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Ob()))}zc(){return this.S}Dc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Pa(),this.Y&&(this.S%=this.ga()),this.s.stop(0)):this.ta=!1:this.ta&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ia,this.s.connect(this.G),this.rb=this.s,this.s.onended=this.fc,this.s.loop=this.Y,T(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.kc=U(this),this.ic=this.S,this.ta=!1)}Jc(b){super.Jc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Yd=-1;this.T=this.jd="";this.o=null}j(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.jd,params:this.o}}}
self.ve=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.te=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Db=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.wb=W(this);this.wb.gain.value=c;this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i);this.Db.connect(this.X);this.X.connect(this.wb);this.wb.connect(this.Db)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Db.disconnect();
this.X.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.jb.vd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.wb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.se=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Od=this.Nd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.vb=this.g.createConvolver();this.vb.normalize=c;this.vb.buffer=a;this.v.connect(this.vb);this.v.connect(this.h);this.vb.connect(this.i)}j(){this.v.disconnect();this.vb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Nd;b.bufferUrl="";b.bufferType=this.Od;return b}};
self.we=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.xb=W(this);this.xb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.xb);this.xb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.xb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.xb.gain,a/100,c,d)}}};
self.ye=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.xe=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.jb.vd;switch(b){case 4:this.o[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.Ae=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.l.pan,a,c,d)}}};
self.Be=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ze=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Ib=W(this);this.Ib.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Ib.gain);this.C.start(0);this.v.connect(this.Ib);this.v.connect(this.h);this.Ib.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Ib.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.ue=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=W(this);this.mc=W(this);this.lc=W(this);b=d;.01>b&&(b=.01);this.mc.gain.value=b;this.lc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.pc=this.g.createWaveShaper();this.Pc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Pc[32768+e]=f,this.Pc[32768-
e-1]=-f;this.pc.curve=this.Pc;this.v.connect(this.mc);this.v.connect(this.h);this.mc.connect(this.pc);this.pc.connect(this.lc);this.lc.connect(this.i)}j(){this.v.disconnect();this.mc.disconnect();this.pc.disconnect();this.lc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.re=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.qe=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Ud=new Float32Array(this.l.frequencyBinCount);this.ie=new Uint8Array(a);this.ge=this.cb=0;b=this.u;b.Ua.add(this);S(b)}j(){this.u.Ua.delete(this);this.l.disconnect();super.j()}Sa(){this.l.getFloatFrequencyData(this.Ud);this.l.getByteTimeDomainData(this.ie);const b=this.l.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.ie[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.Pe;this.cb=c(this.cb);this.ge=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Lb(b,a){a=a.type;let c=!0;0===a?c=await Mb():1===a&&(c=await Nb());m(b,"permission-result",{type:a,result:c})}
async function Mb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Nb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.wa.Da(class extends self.va{constructor(b){super(b,"touch");p(this,"request-permission",a=>Lb(this,a))}});"use strict";
async function Ob(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.wa.Da(class extends self.va{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Qb()],["request-persistent",()=>Ob()]])}async Qb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
self.wa.Da(class extends self.va{constructor(b){super(b,"mouse");v(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.m.xd().requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{m(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{m(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";
self.wa.Da(class extends self.va{constructor(b){super(b,"avix-pokisdk-forc3");this.Sc=this.Xb=this.da=!1;v(this,[["InitPoki",this.Je.bind(this)],["NotifyGameplayStart",this.Qe.bind(this)],["NotifyGameplayStop",this.Ac.bind(this)],["HappyTime",this.Ie.bind(this)],["RequestCommercialBreak",this.Re.bind(this)],["RequestRewardedBreak",this.Se.bind(this)],["SetDebugMode",this.Cd.bind(this)],["GameLoadingFinished",this.He.bind(this)]])}He(){this.da&&!this.Sc&&(this.Sc=!0,globalThis.PokiSDK.gameLoadingFinished())}Qe(){this.da&&(this.Sc||
console.log("Don't forget to send the Loading Finished Notification, or configure the Poki Plugin to manage it automatically."),this.Xb=!0,globalThis.PokiSDK.gameplayStart())}Ac(){this.da&&(this.Xb=!1,globalThis.PokiSDK.gameplayStop())}Ie({Tf:b}){this.da&&globalThis.PokiSDK.happyTime(b)}Re(){if(!this.da)return{result:!1,Lb:!1};this.Xb&&this.Ac();m(this,"SuspendRuntime");return globalThis.PokiSDK.commercialBreak().then(()=>{m(this,"ResumeRuntime");return{result:!0,Lb:!1}}).catch(b=>{console.error(b);
return{result:!1,Lb:b}})}Se(){if(!this.da)return{result:!1,Lb:!1};this.Xb&&this.Ac();m(this,"SuspendRuntime");return globalThis.PokiSDK.rewardedBreak().then(b=>{m(this,"ResumeRuntime");return{result:b,Lb:!1}}).catch(b=>{console.error(b);return{result:!1,Lb:b}})}Cd({enable:b}){this.da&&globalThis.PokiSDK.setDebug(b)}Je({Rf:b,preventScroll:a}){if("undefined"!==typeof globalThis.PokiSDK){a&&this.preventScroll();this.da=!0;let c=!1;return globalThis.PokiSDK.init().then(()=>{console.log("Poki SDK successfully initialized");
return{loaded:this.da,oe:c}}).catch(()=>{console.log("Initialized, but the user likely has adblock");c=!0;return{loaded:this.da,oe:c}}).finally(()=>{b&&this.Cd(!0);globalThis.PokiSDK.gameLoadingStart()})}console.log("Poki SDK failed to load");return Promise.resolve({loaded:this.da,oe:!1})}preventScroll(){window.addEventListener("keydown",b=>{["ArrowDown","ArrowUp"," "].includes(b.key)&&b.preventDefault()});window.addEventListener("wheel",b=>b.preventDefault(),{passive:!1})}});"use strict";
function Pb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Qb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Rb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Sb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Tb(){const b=await Ub();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}
async function Vb(b){if(!b.Ma)try{b.Ma=await navigator.wakeLock.request("screen"),b.Ma.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ma=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Wb(b){const a=await Ub();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Ub(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Pb(b),Qb(b),Rb(b),Sb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.wa.Da(class extends self.va{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>Tb()],["request-wake-lock",()=>Vb(this)],["release-wake-lock",()=>{this.Ma&&(this.Ma.release(),this.Ma=null)}]]);window.addEventListener("resize",()=>Wb(this));this.Ma=null}});
